base:
  server_name: video_surveillance
  server_host: 0.0.0.0
  server_port: 5000
  log_path: ./logs/video_surveillance
  env: dev
  ai_config_path: ./ai/
  real_mqtt: true
mqtt:
  user: pub
  pwd: pub
  topic: mytopic/news
  host: 127.0.0.1
  port: 1883
  bind_address: ''
  bind_port: 0
  keepalive: 60
  qos: 0

